


    # 准备输出txt文件
    output_dir = shared_context.std_video_path.parent
    txt_path = output_dir / "maidata.txt"
    if os.path.exists(txt_path):
        os.remove(txt_path)

    # 写入文件头
    video_name = output_dir.name
    with open(txt_path, 'w', encoding='utf-8') as f:
        f.write(f'&title={video_name}\n')
        f.write(f'&artist=default\n')
        f.write(f'&first=0\n')
        f.write(f'&des=Generated by HachimiDX v{app_version}\n\n')

        f.write(f'&des_{chart_lv}=default\n')
        f.write(f'&lv_{chart_lv}=15\n\n')

        f.write(f'&inote_{chart_lv}=({timing_points[0][1]})' + '{1},\n')
        # 打印流速信息
        note_speed_str = f"{note_speed:.2f}" if note_speed else "N/A"
        touch_speed_str = f"{touch_speed:.2f}" if touch_speed else "N/A"
        f.write(f"|| note speed: {note_speed_str}, touch speed: {touch_speed_str}")

    # 打印基础信息
    level_label = ['zero', 'easy', 'basic', 'advanced', 'expert', 'master', 'remaster', 'special']
    print(f"\n{video_name} - {level_label[chart_lv]}")






    # 打印生成的 maidata.txt 路径
    print(f"\nmaidata.txt: {txt_path}")

